env:
  browser: true
  commonjs: true
  es6: true
extends:
  - 'airbnb-base'
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'prettier'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  sourceType: 'module'
  ecmaFeatures:
    modules: true
    jsx: true
  ecmaVersion: 11
plugins:
  - react
rules: { quotes: [2, 'single', 'avoidEscape': true] }
